GRANT DBA TO SA;

CREATE TABLE Editora
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE Genero
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE Localizacao
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL
);

CREATE TABLE Autor
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(255) NOT NULL,
    favorito  BOOLEAN      NOT NULL,
    biografia VARCHAR(5000)
);
-- Tabela principal: Livro
CREATE TABLE Livro
(
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo         VARCHAR(255) NOT NULL,
    lido           BOOLEAN      NOT NULL,
    ano_publicacao INT          NOT NULL,
    editora_id     INT          NOT NULL,
    localizacao_id INT          NOT NULL,
    quantidade     INT          NOT NULL,
    classificacao  INT,
    data_leitura   DATE,
    comentario     VARCHAR(5000),
    sinopse        VARCHAR(5000),
    favorito       BOOLEAN,
    FOREIGN KEY (editora_id) REFERENCES Editora (id) ON DELETE CASCADE,
    FOREIGN KEY (localizacao_id) REFERENCES Localizacao (id) ON DELETE CASCADE
);

CREATE TABLE livro_genero
(
    livro_id  INT NOT NULL,
    genero_id INT NOT NULL,
    PRIMARY KEY (livro_id, genero_id),
    FOREIGN KEY (livro_id) REFERENCES Livro (id) ON DELETE CASCADE,
    FOREIGN KEY (genero_id) REFERENCES Genero (id) ON DELETE CASCADE
);


CREATE TABLE livro_autor
(
    livro_id INT NOT NULL,
    autor_id INT NOT NULL,
    PRIMARY KEY (livro_id, autor_id),
    FOREIGN KEY (livro_id) REFERENCES Livro (id) ON DELETE CASCADE,
    FOREIGN KEY (autor_id) REFERENCES Autor (id) ON DELETE CASCADE
);