-- Tabela principal: Livro
CREATE TABLE Livro
(
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,                  -- Chave primária com geração automática
    titulo         VARCHAR(255) NOT NULL,                                             -- Atributo título
    lido           BOOLEAN      NOT NULL,                                             -- Atributo para indicar se o livro foi lido
    ano_publicacao INT          NOT NULL,                                             -- Atributo para o ano de publicação
    editora_id     VARCHAR(255) NOT NULL,                                             -- Chave estrangeira para a Editora
    localizacao_id VARCHAR(255) NOT NULL,                                             -- Chave estrangeira para a Localização
    quantidade     INT          NOT NULL,                                             -- Atributo para quantidade de livros
    classificacao  INT,                                                               -- Atributo para a classificação (opcional)
    data_leitura   DATE,                                                              -- Atributo para a data de leitura
    comentario     VARCHAR(5000),                                                     -- Atributo para o comentário
    FOREIGN KEY (editora_id) REFERENCES Editora (nome) ON DELETE CASCADE,             -- Relacionamento com Editora
    FOREIGN KEY (localizacao_id) REFERENCES Localizacao (descricao) ON DELETE CASCADE -- Relacionamento com Localizacao
);

-- Tabela de junção entre Livro e Genero (Many-to-Many)
CREATE TABLE livro_genero
(
    livro_id  INT          NOT NULL,                                   -- Chave estrangeira para Livro
    genero_id VARCHAR(255) NOT NULL,                                   -- Chave estrangeira para Genero
    PRIMARY KEY (livro_id, genero_id),                                 -- Combinação única de livro e genero
    FOREIGN KEY (livro_id) REFERENCES Livro (id) ON DELETE CASCADE,    -- Relacionamento com Livro
    FOREIGN KEY (genero_id) REFERENCES Genero (nome) ON DELETE CASCADE -- Relacionamento com Genero
);

-- Tabela de junção entre Livro e Autor (Many-to-Many)
CREATE TABLE livro_autor
(
    livro_id INT          NOT NULL,                                  -- Chave estrangeira para Livro
    autor_id VARCHAR(255) NOT NULL,                                  -- Chave estrangeira para Autor
    PRIMARY KEY (livro_id, autor_id),                                -- Combinação única de livro e autor
    FOREIGN KEY (livro_id) REFERENCES Livro (id) ON DELETE CASCADE,  -- Relacionamento com Livro
    FOREIGN KEY (autor_id) REFERENCES Autor (nome) ON DELETE CASCADE -- Relacionamento com Autor
);